step add to login to ec2

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -7,178 +7,149 @@ on:
   pull_request:
     branches:
       - master
+env:
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
 jobs:
-  connect:
-    runs-on: ubuntu-latest  # Or another compatible runner
+  build-and-push-images:
+    runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3  # Checkout your code repository
+      - name: Checkout code
+        uses: actions/checkout@v2  # Fetches the entire repository code    
 
-      - name: Configure AWS credentials
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Build and push Docker images
         env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+          IMAGE_TAG: ${{ github.sha }}
         run: |
-          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
-          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+          set -e  # Exit immediately if a command exits with a non-zero status
 
-      - name: Connect to EC2 (using SSH key)  # Optional, adjust based on your key format
-        run: |
-          echo ${{ secrets.SSH_PRIVATE_KEY }} | tr -d '\r' | tr -d '\n' | ssh-keygen -i /dev/stdin -f mykey
-          chmod 600 mykey
-          ssh -i mykey ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_IP }}  # Use username if needed
+          # Build and push Docker images for each service
+          build_and_push() {
+            local service_directory=$1
+            local service_name=$2
 
-          # Remove the temporary key after use
-          rm mykey
-  # build-and-push-images:
-  #   runs-on: ubuntu-latest
+            if [ -d "$service_directory" ]; then
+              cd $service_directory
+              docker build -t $DOCKER_USERNAME/sgproject:$service_name -f Dockerfiles/Dockerfile .
+              docker tag $DOCKER_USERNAME/sgproject:$service_name $DOCKER_USERNAME/sgproject:$service_name-$IMAGE_TAG
+              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
+              docker push $DOCKER_USERNAME/sgproject:$service_name-$IMAGE_TAG
+              cd $( [[ "$service_directory" == "frontend/studio-ghibli" || "$service_directory" == "backend"* ]] && echo "../.." || echo ".." )
+            else
+              echo "Directory $service_directory not found."
+              exit 1
+            fi
+          }
 
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2  # Fetches the entire repository code    
+          build_and_push "admin_frontend" "admin_frontend"
+          build_and_push "frontend/studio-ghibli" "studio_ghibli_frontend"
+          build_and_push "backend/gateway" "gateway"
+          build_and_push "backend/courses" "courses"
+          build_and_push "backend/enrollment" "enrollment"
+          build_and_push "backend/customers" "customers"
+          build_and_push "backend/users" "users"
 
-  #     - name: Login to Docker Hub
-  #       uses: docker/login-action@v2
-  #       with:
-  #         username: ${{ secrets.DOCKER_USERNAME }}
-  #         password: ${{ secrets.DOCKER_PASSWORD }}
+  terraform:
+    name: 'Terraform Plan and Apply'
+    runs-on: ubuntu-latest
 
-  #     - name: Build and push Docker images
-  #       env:
-  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-  #         IMAGE_TAG: ${{ github.sha }}
-  #       run: |
-  #         set -e  # Exit immediately if a command exits with a non-zero status
+    steps:
+    - name: 'Checkout Repository'
+      uses: actions/checkout@v2
 
-  #         # Build and push Docker images for each service
-  #         build_and_push() {
-  #           local service_directory=$1
-  #           local service_name=$2
+    - name: 'Set Up Terraform'
+      uses: hashicorp/setup-terraform@v1
+      with:
+        terraform_version: 1.0.9
 
-  #           if [ -d "$service_directory" ]; then
-  #             cd $service_directory
-  #             docker build -t $DOCKER_USERNAME/sgproject:$service_name -f Dockerfiles/Dockerfile .
-  #             docker tag $DOCKER_USERNAME/sgproject:$service_name $DOCKER_USERNAME/sgproject:$service_name-$IMAGE_TAG
-  #             echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-  #             docker push $DOCKER_USERNAME/sgproject:$service_name-$IMAGE_TAG
-  #             cd $( [[ "$service_directory" == "frontend/studio-ghibli" || "$service_directory" == "backend"* ]] && echo "../.." || echo ".." )
-  #           else
-  #             echo "Directory $service_directory not found."
-  #             exit 1
-  #           fi
-  #         }
+    - name: 'Install Terrascan'
+      run: |
+        curl -L https://github.com/tenable/terrascan/releases/download/v1.19.1/terrascan_1.19.1_Linux_x86_64.tar.gz -o terrascan.tar.gz
+        tar -xzf terrascan.tar.gz
+        chmod +x terrascan
+        sudo mv terrascan /usr/local/bin/terrascan
+        terrascan version
 
-  #         build_and_push "admin_frontend" "admin_frontend"
-  #         build_and_push "frontend/studio-ghibli" "studio_ghibli_frontend"
-  #         build_and_push "backend/gateway" "gateway"
-  #         build_and_push "backend/courses" "courses"
-  #         build_and_push "backend/enrollment" "enrollment"
-  #         build_and_push "backend/customers" "customers"
-  #         build_and_push "backend/users" "users"
+    - name: 'List Directory Contents'
+      run: ls -la ./iac
 
-  # terraform:
-  #   name: 'Terraform Plan and Apply'
-  #   runs-on: ubuntu-latest
+    - name: 'Run Terrascan'
+      run: terrascan scan -i terraform -d ./iac
+      continue-on-error: true # Temporarily allow pipeline to continue on error for debugging
 
-  #   steps:
-  #   - name: 'Checkout Repository'
-  #     uses: actions/checkout@v2
+    - name: 'Terraform Init'
+      working-directory: ./iac
+      run: terraform init
 
-  #   - name: 'Set Up Terraform'
-  #     uses: hashicorp/setup-terraform@v1
-  #     with:
-  #       terraform_version: 1.0.9
+    - name: 'Terraform Validate'
+      working-directory: ./iac
+      run: terraform validate
 
-  #   - name: 'Install Terrascan'
-  #     run: |
-  #       curl -L https://github.com/tenable/terrascan/releases/download/v1.19.1/terrascan_1.19.1_Linux_x86_64.tar.gz -o terrascan.tar.gz
-  #       tar -xzf terrascan.tar.gz
-  #       chmod +x terrascan
-  #       sudo mv terrascan /usr/local/bin/terrascan
-  #       terrascan version
+    - name: 'Terraform Plan'
+      working-directory: ./iac
+      run: terraform plan
 
-  #   - name: 'List Directory Contents'
-  #     run: ls -la ./iac
+    - name: 'Terraform Apply'
+      working-directory: ./iac
+      run: terraform apply -auto-approve
 
-  #   - name: 'Run Terrascan'
-  #     run: terrascan scan -i terraform -d ./iac
-  #     continue-on-error: true # Temporarily allow pipeline to continue on error for debugging
+    - name: 'Get Terraform Output'
+      id: output
+      working-directory: ./iac
+      run: echo "::set-output name=instance_public_ip::$(terraform output -raw instance_public_ip)"
 
-  #   - name: 'Terraform Init'
-  #     working-directory: ./iac
-  #     env:
-  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #     run: terraform init
+  deploy:
+    runs-on: ubuntu-latest
+    needs: [terraform,build-and-push-images]  # This job depends on the successful completion of the 'terraform' job
 
-  #   - name: 'Terraform Validate'
-  #     working-directory: ./iac
-  #     env:
-  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #     run: terraform validate
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-  #   - name: 'Terraform Plan'
-  #     working-directory: ./iac
-  #     env:
-  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #     run: terraform plan
+    - name: Download SSH key
+      run: |
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
+        chmod 600 deploy_key
 
-  #   - name: 'Terraform Apply'
-  #     if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-  #     working-directory: ./iac
-  #     env:
-  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #     run: terraform apply -auto-approve
+    - name: Connect to EC2 instance via SSH
+      env:
+        SERVER_PUBLIC_IP: ${{ needs.terraform.outputs.instance_public_ip }}
+      run: |
+        ssh -o StrictHostKeyChecking=no -i deploy_key ubuntu@${{ env.SERVER_PUBLIC_IP }}
 
-  # deploy:
-  #   runs-on: ubuntu-latest
-  #   needs: terraform  # This job depends on the successful completion of the 'terraform' job
+    - name: Pull Docker images
+      env:
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        IMAGE_TAG: ${{ github.sha }}
+      run: |
+        docker pull $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
+        docker pull $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
+        docker pull $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
+        docker pull $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
+        docker pull $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
+        docker pull $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
+        docker pull $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG
 
-  #   steps:
-  #   - name: Checkout code
-  #     uses: actions/checkout@v2
-
-  #   - name: Set SSH key environment variable
-  #     run: echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
-
-  #   - name: Download SSH key
-  #     if: env.SSH_PRIVATE_KEY
-  #     run: |
-  #       echo "${{ env.SSH_PRIVATE_KEY }}" > deploy_key
-  #       chmod 600 deploy_key
-
-  #   - name: Connect to EC2 instance via SSH
-  #     if: env.SSH_PRIVATE_KEY
-  #     run: |
-  #       ssh -o StrictHostKeyChecking=no -i deploy_key ubuntu@${{ secrets.EC2_IP }}
-
-  #   - name: Pull Docker images
-  #     env:
-  #       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-  #       IMAGE_TAG: ${{ github.sha }}
-  #     run: |
-  #       docker pull $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
-  #       docker pull $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
-  #       docker pull $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
-  #       docker pull $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
-  #       docker pull $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
-  #       docker pull $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
-  #       docker pull $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG
-
-  #   - name: Run Docker containers
-  #     env:
-  #       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-  #       IMAGE_TAG: ${{ github.sha }}
-  #     run: |
-  #       docker run -d -p 80:80 $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
-  #       docker run -d -p 8080:8080 $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
-  #       docker run -d -p 8880:8880 $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
-  #       docker run -d -p 8881:8881 $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
-  #       docker run -d -p 8882:8882 $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
-  #       docker run -d -p 8883:8883 $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
-  #       docker run -d -p 8884:8884 $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG
+    - name: Run Docker containers
+      env:
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        IMAGE_TAG: ${{ github.sha }}
+      run: |
+        docker run -d -p 80:80 $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
+        docker run -d -p 8080:8080 $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
+        docker run -d -p 8880:8880 $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
+        docker run -d -p 8881:8881 $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
+        docker run -d -p 8882:8882 $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
+        docker run -d -p 8883:8883 $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
+        docker run -d -p 8884:8884 $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG
