Verifying old yml file to see the issues

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -8,18 +8,13 @@ on:
     branches:
       - master
 
-env:
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
-
 jobs:
   build-and-push-images:
-    name: 'Build and Push Docker Images'
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v2  # Fetches the entire repository code    
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -33,8 +28,10 @@ jobs:
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
           IMAGE_TAG: ${{ github.sha }}
         run: |
-          set -e
+        
+          set -e  # Exit immediately if a command exits with a non-zero status
 
+          # Build and push Docker images for each service
           build_and_push() {
             local service_directory=$1
             local service_name=$2
@@ -53,126 +50,66 @@ jobs:
           }
 
           build_and_push "admin_frontend" "admin_frontend"
-          # Uncomment these lines as needed for other services
-          # build_and_push "frontend/studio-ghibli" "studio_ghibli_frontend"
-          # build_and_push "backend/gateway" "gateway"
-          # build_and_push "backend/courses" "courses"
-          # build_and_push "backend/enrollment" "enrollment"
-          # build_and_push "backend/customers" "customers"
-          # build_and_push "backend/users" "users"
+          build_and_push "frontend/studio-ghibli" "studio_ghibli_frontend"
+          build_and_push "backend/gateway" "gateway"
+          build_and_push "backend/courses" "courses"
+          build_and_push "backend/enrollment" "enrollment"
+          build_and_push "backend/customers" "customers"
+          build_and_push "backend/users" "users"
 
-  terraform-build:
+  terraform:
     name: 'Terraform Plan and Apply'
     runs-on: ubuntu-latest
-    outputs:
-      target_ec2_ip: ${{ steps.get_ip.outputs.target_ip }}
-    steps:
-      - name: 'Checkout Repository'
-        uses: actions/checkout@v2
-
-      - name: 'Set Up Terraform'
-        uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 1.0.9
-
-      - name: 'Install Terrascan'
-        run: |
-          curl -L https://github.com/tenable/terrascan/releases/download/v1.19.1/terrascan_1.19.1_Linux_x86_64.tar.gz -o terrascan.tar.gz
-          tar -xzf terrascan.tar.gz
-          chmod +x terrascan
-          sudo mv terrascan /usr/local/bin/terrascan
-          terrascan version
-
-      - name: 'List Directory Contents'
-        run: ls -la ./iac
-
-      - name: 'Run Terrascan'
-        run: terrascan scan -i terraform -d ./iac
-        continue-on-error: true
-
-      - name: 'Terraform Init'
-        working-directory: ./iac
-        run: terraform init
-
-      - name: 'Terraform Validate'
-        working-directory: ./iac
-        run: terraform validate
-
-      - name: Debug AWS Credentials
-        run: |
-          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
-          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        
-
-      - name: Execute Terraform Plan
-        working-directory: ./iac
-        run: |
-          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
-          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
-          terraform plan -out=tfplan -input=false -lock=true -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="AWS_REGION=${{ secrets.AWS_REGION }}"
-
-      - name: 'Terraform Apply'
-        working-directory: ./iac
-        id: get_ip
-        run: |
-          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
-          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          terraform apply -auto-approve -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="AWS_REGION=${{ secrets.AWS_REGION }}"
-          instance_ip=$(terraform output instance_public_ip)
-          match=$(echo "$instance_ip" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')  # Extract digits and dots
-          echo "::set-output name=target_ip::$match"
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: [terraform-build, build-and-push-images]
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+    - name: 'Checkout Repository'
+      uses: actions/checkout@v2
 
-      - name: Download SSH key
-        run: |
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sgproject
-          chmod 400 sgproject
+    - name: 'Set Up Terraform'
+      uses: hashicorp/setup-terraform@v1
+      with:
+        terraform_version: 1.0.9
 
-      - name: Connect to EC2 instance via SSH
-        run: |
-          echo "Connecting to ${{ needs.terraform-build.outputs.target_ec2_ip }}"
-          ssh -o StrictHostKeyChecking=no -i sgproject ubuntu@${{ needs.terraform-build.outputs.target_ec2_ip }}
+    - name: 'Install Terrascan'
+      run: |
+        curl -L https://github.com/tenable/terrascan/releases/download/v1.19.1/terrascan_1.19.1_Linux_x86_64.tar.gz -o terrascan.tar.gz
+        tar -xzf terrascan.tar.gz
+        chmod +x terrascan
+        sudo mv terrascan /usr/local/bin/terrascan
+        terrascan version
 
-      - name: Pull Docker images
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          echo "Pulling Docker images on ${{ needs.terraform-build.outputs.target_ec2_ip }}"
-          ssh -o StrictHostKeyChecking=no -i sgproject ubuntu@${{ needs.terraform-build.outputs.target_ec2_ip }} << EOF
-            docker pull $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
-            # Uncomment these lines as needed
-            # docker pull $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
-            # docker pull $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
-            # docker pull $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
-            # docker pull $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
-            # docker pull $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
-            # docker pull $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG
-          EOF
+    - name: 'List Directory Contents'
+      run: ls -la ./iac
 
-      - name: Run Docker containers
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          echo "Running Docker containers on ${{ needs.terraform-build.outputs.target_ec2_ip }}"
-          ssh -o StrictHostKeyChecking=no -i sgproject ubuntu@${{ needs.terraform-build.outputs.target_ec2_ip }} << EOF
-            # Uncomment these lines as needed
-            # docker run -d -p 80:80 $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
-            docker run -d -p 8080:8080 $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
-            # docker run -d -p 8880:8880 $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
-            # docker run -d -p 8881:8881 $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
-            # docker run -d -p 8882:8882 $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
-            # docker run -d -p 8883:8883 $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
-            # docker run -d -p 8884:8884 $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG
-          EOF
+    - name: 'Run Terrascan'
+      run: terrascan scan -i terraform -d ./iac
+      continue-on-error: true # Temporarily allow pipeline to continue on error for debugging
+
+    - name: 'Terraform Init'
+      working-directory: ./iac
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      run: terraform init
+
+    - name: 'Terraform Validate'
+      working-directory: ./iac
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      run: terraform validate
+
+    - name: 'Terraform Plan'
+      working-directory: ./iac
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      run: terraform plan
+
+    - name: 'Terraform Apply'
+      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+      working-directory: ./iac
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      run: terraform apply -auto-approve
